In [11]:
import numpy as np

my_list = [10,11,12,13,14]
my_list_np = np.array(my_list)

my_list_np.dtype

for i in my_list:
    print(i)

for i in my_list_np:
    print(i)



10
11
12
13
14
10
11
12
13
14


In [3]:
my_tuple = (10,11,12,13,14)
my_tuple_np = np.array(my_tuple)

for i in my_tuple_np:
    print(i)

my_tuple_np.argmax()
my_tuple_np.argmin()



10
11
12
13
14


4

In [13]:
def max_min(list):
    max = np.argmax(list)
    min = np.argmin(list)
    return min , max 

list_test = (5,4,37,48,1)

max_min(list_test)


(4, 3)

In [9]:
my_matrice = np.array([[1,2,3],
                       [4,5,6]])
my_matrice.shape
my_matrice.diagonal()

array([1, 5])

In [10]:
arr1 = np.array([23,45,33,78,12])
arr2 = np.array([125,456,889,587,99])

addition = arr1 + arr2 

subtraction = arr1 - arr2 

multiplication = arr1 * arr2 

division = arr1 / arr2 

print(addition)
print(subtraction)
print(multiplication)
print(division)


[148 501 922 665 111]
[-102 -411 -856 -509  -87]
[ 2875 20520 29337 45786  1188]
[0.184      0.09868421 0.03712036 0.13287905 0.12121212]


In [ ]:
random_list = np.random.randint(1,101,20)

greater_than_50 = random_array[random_list]
